### PR TITLE
Add starter kit support

### PR DESCRIPTION
**Pull request by dolph**
Ready for review & merging.

### CODE REVIEW

**Comment by dolph** [comment]
This also bumps both disk and memory requirements to 512MB. Despite the "out of memory" kill error I was getting, it turned out the app was actually exceeding disk space shortly after startup (around 275-285MB seems to be normal disk usage). I'm bumping memory as well, because it's running at about 245MB (and likely paging, if it can).

**Comment by stevemart** [comment]
@dolph darn, was hoping to keep this one under 256MB since that's within the free-tier for ibm cloud

**Comment by dolph** [comment]
@stevemart for memory or disk? we could probably optimize the app to manage memory/disk better, but it's broken otherwise (perhaps just as a result of the API responses from Watson services?).

**Comment by markstur** [comment]
@dolph memory

**Comment by dolph** [comment]
Proposed a reduction in memory footprint in PR #37

**Pull request merged**
