### PR TITLE
add metrics tracker integration

### PR DESCRIPTION
**Pull request by stevemart**

### CODE REVIEW

**Comment by stevemart** [comment]
@animeshsingh three things I'm unclear about:

1. I grabbed the new UUID from https://metrics-tracker.mybluemix.net/stats -- is that correct?
2. The `id`field in `repository.yaml`, is that just the github repo name?
3. Is the recommendation to replace the existing tracker or use both?

**Comment by animeshsingh** [comment]
@stevemart sorry missed this - do these questions sill exist now that you updated few?

**Comment by stevemart** [comment]
@animeshsingh the questions still stand :)

**Comment by animeshsingh** [comment]
@stevemart i though since many patterns were onboarded - these questions remains solved. Id field is github repo - yes. Old tracker has stopped taking any requests, so please remove from all Journeys. 

For CF based apps - we don`t need language, as it can be derived from SDK type.

**Pull request closed without merging**
